### PR TITLE
Fix permissive

### LINKED ISSUE #64: Build errors with MSVC /permissive- flag
**Issue:**

Library won't compile with MSVC if /permissive- flag is used.

**Proposed solution:**
Patch provided.

[0001-Allow-permissive-build-with-MSVC.patch](https://github.com/ami-iit/matio-cpp/files/10464540/0001-Allow-permissive-build-with-MSVC.patch)

### PR DESCRIPTION
**Pull request by S-Dafarra**
Fixes #64

### CODE REVIEW

**Comment by S-Dafarra** [comment]
The conda-forge worflow was disabled. Trying to close the PR and open it again to trigger it

**Comment by S-Dafarra** [comment]
For some reason the https://github.com/ami-iit/matio-cpp/blob/bece761c9902c1b87925b3b6e3a621f495d508f7/.github/workflows/conda-forge-ci.yml#L51 causes the error 
```
c1xx : fatal error C1083: Cannot open source file: 'C:/Program': No such file or directory [D:\a\matio-cpp\matio-cpp\build\matioCpp.vcxproj]
  permissive-
c1xx : fatal error C1083: Cannot open source file: 'Files/Git/permissive-': No such file or directory [D:\a\matio-cpp\matio-cpp\build\matioCpp.vcxproj]
  Variable.cpp
  ConversionUtilities.cpp
  MatvarHandler.cpp
  SharedMatvar.cpp
  WeakMatvar.cpp
  CellArray.cpp
  File.cpp
  Struct.cpp
  StructArray.cpp
  ExogenousConversions.cpp
  Generating Code...
  Building Custom Rule D:/a/matio-cpp/matio-cpp/build/_deps/visit_struct-src/CMakeLists.txt
  Program
c1xx : fatal error C1083: Cannot open source file: 'C:/Program': No such file or directory [D:\a\matio-cpp\matio-cpp\build\_deps\visit_struct-build\test_fully_visitable.vcxproj]
  permissive-
c1xx : fatal error C1083: Cannot open source file: 'Files/Git/permissive-': No such file or directory [D:\a\matio-cpp\matio-cpp\build\_deps\visit_struct-build\test_fully_visitable.vcxproj]
  test_fully_visitable.cpp
  Generating Code...
  Building Custom Rule D:/a/matio-cpp/matio-cpp/build/_deps/visit_struct-src/CMakeLists.txt
  Program
c1xx : fatal error C1083: Cannot open source file: 'C:/Program': No such file or directory [D:\a\matio-cpp\matio-cpp\build\_deps\visit_struct-build\test_visit_struct.vcxproj]
  permissive-
c1xx : fatal error C1083: Cannot open source file: 'Files/Git/permissive-': No such file or directory [D:\a\matio-cpp\matio-cpp\build\_deps\visit_struct-build\test_visit_struct.vcxproj]
  test_visit_struct.cpp
  Generating Code...
  Building Custom Rule D:/a/matio-cpp/matio-cpp/build/_deps/visit_struct-src/CMakeLists.txt
  Program
c1xx : fatal error C1083: Cannot open source file: 'C:/Program': No such file or directory [D:\a\matio-cpp\matio-cpp\build\_deps\visit_struct-build\test_visit_struct_intrusive.vcxproj]
  permissive-
c1xx : fatal error C1083: Cannot open source file: 'Files/Git/permissive-': No such file or directory [D:\a\matio-cpp\matio-cpp\build\_deps\visit_struct-build\test_visit_struct_intrusive.vcxproj]
  test_visit_struct_intrusive.cpp
  Generating Code...
```
as if ``/permissive-`` gets interpreted as a file

**Comment by S-Dafarra** [comment]
cc @xaltmiles

**Comment by xaltmiles** [comment]
Looks good!

**Comment by traversaro** [comment]
> For some reason the
> 
> https://github.com/ami-iit/matio-cpp/blob/bece761c9902c1b87925b3b6e3a621f495d508f7/.github/workflows/conda-forge-ci.yml#L51
> causes the error
> 
> ```
> c1xx : fatal error C1083: Cannot open source file: 'C:/Program': No such file or directory [D:\a\matio-cpp\matio-cpp\build\matioCpp.vcxproj]
>   permissive-
> c1xx : fatal error C1083: Cannot open source file: 'Files/Git/permissive-': No such file or directory [D:\a\matio-cpp\matio-cpp\build\matioCpp.vcxproj]
>   Variable.cpp
>   ConversionUtilities.cpp
>   MatvarHandler.cpp
>   SharedMatvar.cpp
>   WeakMatvar.cpp
>   CellArray.cpp
>   File.cpp
>   Struct.cpp
>   StructArray.cpp
>   ExogenousConversions.cpp
>   Generating Code...
>   Building Custom Rule D:/a/matio-cpp/matio-cpp/build/_deps/visit_struct-src/CMakeLists.txt
>   Program
> c1xx : fatal error C1083: Cannot open source file: 'C:/Program': No such file or directory [D:\a\matio-cpp\matio-cpp\build\_deps\visit_struct-build\test_fully_visitable.vcxproj]
>   permissive-
> c1xx : fatal error C1083: Cannot open source file: 'Files/Git/permissive-': No such file or directory [D:\a\matio-cpp\matio-cpp\build\_deps\visit_struct-build\test_fully_visitable.vcxproj]
>   test_fully_visitable.cpp
>   Generating Code...
>   Building Custom Rule D:/a/matio-cpp/matio-cpp/build/_deps/visit_struct-src/CMakeLists.txt
>   Program
> c1xx : fatal error C1083: Cannot open source file: 'C:/Program': No such file or directory [D:\a\matio-cpp\matio-cpp\build\_deps\visit_struct-build\test_visit_struct.vcxproj]
>   permissive-
> c1xx : fatal error C1083: Cannot open source file: 'Files/Git/permissive-': No such file or directory [D:\a\matio-cpp\matio-cpp\build\_deps\visit_struct-build\test_visit_struct.vcxproj]
>   test_visit_struct.cpp
>   Generating Code...
>   Building Custom Rule D:/a/matio-cpp/matio-cpp/build/_deps/visit_struct-src/CMakeLists.txt
>   Program
> c1xx : fatal error C1083: Cannot open source file: 'C:/Program': No such file or directory [D:\a\matio-cpp\matio-cpp\build\_deps\visit_struct-build\test_visit_struct_intrusive.vcxproj]
>   permissive-
> c1xx : fatal error C1083: Cannot open source file: 'Files/Git/permissive-': No such file or directory [D:\a\matio-cpp\matio-cpp\build\_deps\visit_struct-build\test_visit_struct_intrusive.vcxproj]
>   test_visit_struct_intrusive.cpp
>   Generating Code...
> ```
> 
> as if `/permissive-` gets interpreted as a file

That is because the CMake command is running under Git Bash. In Git Bash, whenever a `/` is seen, Git Bash does strange substitution rules to change it to `C:\Program Files\Git`. For example see the following snipped that you can run on Git Bash:
~~~
STraversaro@IITICUBLAP257 MINGW64 ~
$ export TESTVAR=/permissive-

STraversaro@IITICUBLAP257 MINGW64 ~
$ echo $TESTVAR
/permissive-

STraversaro@IITICUBLAP257 MINGW64 ~
$ cmd
Microsoft Windows [Version 10.0.22000.1335]
(c) Microsoft Corporation. All rights reserved.

C:\Users\STraversaro>echo %TESTVAR%
C:/Program Files/Git/permissive-
~~~

An alternative solution could be either to pass the permissive options as `//permissive-`:
~~~
STraversaro@IITICUBLAP257 MINGW64 ~
$ export TESTVAR=//permissive-

STraversaro@IITICUBLAP257 MINGW64 ~
$ echo $TESTVAR
//permissive-

STraversaro@IITICUBLAP257 MINGW64 ~
$ cmd
Microsoft Windows [Version 10.0.22000.1335]
(c) Microsoft Corporation. All rights reserved.

C:\Users\STraversaro>echo %TESTVAR%
/permissive-
~~~

or run the configuration in `cmd` or `pwsh` , by changing the argument in https://github.com/ami-iit/matio-cpp/blob/e951ef357224501bc3ea77761d1b8900e4862cfa/.github/workflows/conda-forge-ci.yml#L48 to ` cmd /C CALL {0}` or `pwsh`, see https://github.com/marketplace/actions/setup-miniconda#example-2-other-shells .

**Review by traversaro — APPROVED** [review]

**Comment by S-Dafarra** [comment]
> > For some reason the
> > https://github.com/ami-iit/matio-cpp/blob/bece761c9902c1b87925b3b6e3a621f495d508f7/.github/workflows/conda-forge-ci.yml#L51
> > 
> > causes the error
> > ```
> > c1xx : fatal error C1083: Cannot open source file: 'C:/Program': No such file or directory [D:\a\matio-cpp\matio-cpp\build\matioCpp.vcxproj]
> >   permissive-
> > c1xx : fatal error C1083: Cannot open source file: 'Files/Git/permissive-': No such file or directory [D:\a\matio-cpp\matio-cpp\build\matioCpp.vcxproj]
> >   Variable.cpp
> >   ConversionUtilities.cpp
> >   MatvarHandler.cpp
> >   SharedMatvar.cpp
> >   WeakMatvar.cpp
> >   CellArray.cpp
> >   File.cpp
> >   Struct.cpp
> >   StructArray.cpp
> >   ExogenousConversions.cpp
> >   Generating Code...
> >   Building Custom Rule D:/a/matio-cpp/matio-cpp/build/_deps/visit_struct-src/CMakeLists.txt
> >   Program
> > c1xx : fatal error C1083: Cannot open source file: 'C:/Program': No such file or directory [D:\a\matio-cpp\matio-cpp\build\_deps\visit_struct-build\test_fully_visitable.vcxproj]
> >   permissive-
> > c1xx : fatal error C1083: Cannot open source file: 'Files/Git/permissive-': No such file or directory [D:\a\matio-cpp\matio-cpp\build\_deps\visit_struct-build\test_fully_visitable.vcxproj]
> >   test_fully_visitable.cpp
> >   Generating Code...
> >   Building Custom Rule D:/a/matio-cpp/matio-cpp/build/_deps/visit_struct-src/CMakeLists.txt
> >   Program
> > c1xx : fatal error C1083: Cannot open source file: 'C:/Program': No such file or directory [D:\a\matio-cpp\matio-cpp\build\_deps\visit_struct-build\test_visit_struct.vcxproj]
> >   permissive-
> > c1xx : fatal error C1083: Cannot open source file: 'Files/Git/permissive-': No such file or directory [D:\a\matio-cpp\matio-cpp\build\_deps\visit_struct-build\test_visit_struct.vcxproj]
> >   test_visit_struct.cpp
> >   Generating Code...
> >   Building Custom Rule D:/a/matio-cpp/matio-cpp/build/_deps/visit_struct-src/CMakeLists.txt
> >   Program
> > c1xx : fatal error C1083: Cannot open source file: 'C:/Program': No such file or directory [D:\a\matio-cpp\matio-cpp\build\_deps\visit_struct-build\test_visit_struct_intrusive.vcxproj]
> >   permissive-
> > c1xx : fatal error C1083: Cannot open source file: 'Files/Git/permissive-': No such file or directory [D:\a\matio-cpp\matio-cpp\build\_deps\visit_struct-build\test_visit_struct_intrusive.vcxproj]
> >   test_visit_struct_intrusive.cpp
> >   Generating Code...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > as if `/permissive-` gets interpreted as a file
> 
> That is because the CMake command is running under Git Bash. In Git Bash, whenever a starting `/` is seen, Git Bash does strange substitution rules to change it to `C:\Program Files\Git` (see [bmatzelle/gow#196](https://github.com/bmatzelle/gow/issues/196) for example) . For example see the following snipped that you can run on Git Bash:
> 
> ```
> STraversaro@IITICUBLAP257 MINGW64 ~
> $ export TESTVAR=/permissive-
> 
> STraversaro@IITICUBLAP257 MINGW64 ~
> $ echo $TESTVAR
> /permissive-
> 
> STraversaro@IITICUBLAP257 MINGW64 ~
> $ cmd
> Microsoft Windows [Version 10.0.22000.1335]
> (c) Microsoft Corporation. All rights reserved.
> 
> C:\Users\STraversaro>echo %TESTVAR%
> C:/Program Files/Git/permissive-
> ```
> 
> An alternative solution could be either to pass the permissive options as `//permissive-`:
> 
> ```
> STraversaro@IITICUBLAP257 MINGW64 ~
> $ export TESTVAR=//permissive-
> 
> STraversaro@IITICUBLAP257 MINGW64 ~
> $ echo $TESTVAR
> //permissive-
> 
> STraversaro@IITICUBLAP257 MINGW64 ~
> $ cmd
> Microsoft Windows [Version 10.0.22000.1335]
> (c) Microsoft Corporation. All rights reserved.
> 
> C:\Users\STraversaro>echo %TESTVAR%
> /permissive-
> ```
> 
> or run the configuration in `cmd` or `pwsh` , by changing the argument in
> 
> https://github.com/ami-iit/matio-cpp/blob/e951ef357224501bc3ea77761d1b8900e4862cfa/.github/workflows/conda-forge-ci.yml#L48
> 
> to ` cmd /C CALL {0}` or `pwsh`, see https://github.com/marketplace/actions/setup-miniconda#example-2-other-shells .

Ah, good to know, thanks a lot!

I am tempted to change it back, but I guess it can be useful to have the option I added as a check in the future. Merging as is.

**Pull request merged**
