### PR TITLE
Fix compilation matio 1 5 27

### LINKED ISSUE #81: Compilation failure with matio 1.5.27
In conda-forge matio got update to 1.5.17, and this error appeared:

~~~
[6/36] Building CXX object CMakeFiles/matioCpp.dir/src/File.cpp.o
FAILED: CMakeFiles/matioCpp.dir/src/File.cpp.o 
/home/conda/feedstock_root/build_artifacts/matio-cpp-split_1716299022551/_build_env/bin/x86_64-conda-linux-gnu-c++ -DmatioCpp_EXPORTS -I/home/conda/feedstock_root/build_artifacts/matio-cpp-split_1716299022551/work/include -I/home/conda/feedstock_root/build_artifacts/matio-cpp-split_1716299022551/work/build/Autogenerated -isystem /home/conda/feedstock_root/build_artifacts/matio-cpp-split_1716299022551/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/include/eigen3 -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/conda/feedstock_root/build_artifacts/matio-cpp-split_1716299022551/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/matio-cpp-split_1716299022551/work=/usr/local/src/conda/libmatio-cpp-0.2.4 -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/matio-cpp-split_1716299022551/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place=/usr/local/src/conda-prefix -O3 -DNDEBUG -fPIC -MD -MT CMakeFiles/matioCpp.dir/src/File.cpp.o -MF CMakeFiles/matioCpp.dir/src/File.cpp.o.d -o CMakeFiles/matioCpp.dir/src/File.cpp.o -c /home/conda/feedstock_root/build_artifacts/matio-cpp-split_1716299022551/work/src/File.cpp
/home/conda/feedstock_root/build_artifacts/matio-cpp-split_1716299022551/work/src/File.cpp: In member function 'std::vector<std::__cxx11::basic_string<char> > matioCpp::File::variableNames() const':
/home/conda/feedstock_root/build_artifacts/matio-cpp-split_1716299022551/work/src/File.cpp:294:33: error: invalid conversion from 'char* const*' to 'char**' [-fpermissive]
  294 |         char** list = Mat_GetDir(m_pimpl->mat_ptr, &list_size);
      |                       ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                 |
      |                                 char* const*
[7/36] Building CXX object CMakeFiles/matioCpp.dir/src/CellArray.cpp.o
[8/36] Building CXX object CMakeFiles/matioCpp.dir/src/Struct.cpp.o
ninja: build stopped: subcommand failed.
~~~

### PR DESCRIPTION
**Pull request by S-Dafarra**
Fixes #81

### CODE REVIEW

**Comment by traversaro** [comment]
This works fine with older matio versions?

**Comment by S-Dafarra** [comment]
> This works fine with older matio versions?

I tested it on my machine where I did not update and seemed to work fine. I suppose it should be safe since now it is "more restrictive". Worst case I can use ``auto``

**Comment by S-Dafarra** [comment]
> This works fine with older matio versions?

Actually the ``ci`` workflow tests it against the apt version which should be 1.5.17, while the conda version is 1.5.27

**Review by traversaro — APPROVED** [review]

**Comment by traversaro** [comment]
> > This works fine with older matio versions?
> 
> Actually the ``ci`` workflow tests it against the apt version which should be 1.5.21, while the conda version is 1.5.27

Perfect!

**Comment by traversaro** [comment]
> > This works fine with older matio versions?
> 
> Actually the ``ci`` workflow tests it against the apt version which should be 1.5.21, while the conda version is 1.5.27

Perfect!

**Comment by S-Dafarra** [comment]
Thanks @traversaro 

Merging

**Pull request merged**
